export { default as CommunitiesView } from './CommunitiesPage'
export { default as CommunityView } from './CommunityPage'
export { default as CreateNewCommunityView } from './CreateCommunityPage'
export { default as CreateNewPostView } from './CreatePostPage'
export { default as EditPostView } from './EditPostPage'
